#pragma once

#include "Common.hpp"
#include "StreamData.hpp"

#include <YoutubeExplode/Common/Time.hpp>

#include <optional>
#include <string>
#include <vector>

namespace YoutubeExplode::detail {

struct ClosedCaptionTrackData {
    std::optional<std::string> url;
    std::optional<std::string> languageCode;
    std::optional<std::string> languageName;
    bool isAutoGenerated = false;
};

/// Wrapper over the JSON returned by /youtubei/v1/player (or embedded in the watch page).
class PlayerResponse {
public:
    explicit PlayerResponse(Json content) : content_(std::move(content)) {}
    static PlayerResponse parse(const std::string& raw) { return PlayerResponse(parseJson(raw)); }

    std::optional<std::string> playabilityStatus() const;
    std::optional<std::string> playabilityError() const;
    bool isAvailable() const;
    bool isPlayable() const;
    bool isAgeRestricted() const;

    std::optional<std::string> title() const;
    std::optional<std::string> channelId() const;
    std::optional<std::string> author() const;
    std::optional<DateTimeOffset> uploadDate() const;
    std::optional<TimeSpan> duration() const;
    std::vector<ThumbnailData> thumbnails() const;
    std::vector<std::string> keywords() const;
    std::optional<std::string> description() const;
    std::optional<long long> viewCount() const;
    bool isLive() const;

    std::optional<std::string> previewVideoId() const;

    std::optional<std::string> dashManifestUrl() const;
    std::optional<std::string> hlsManifestUrl() const;
    std::vector<StreamData> streams() const;

    std::vector<ClosedCaptionTrackData> closedCaptionTracks() const;

    const Json& json() const noexcept { return content_; }

private:
    const Json* playability() const { return dig(content_, {"playabilityStatus"}); }
    const Json* details() const { return dig(content_, {"videoDetails"}); }

    Json content_;
};

StreamData parseStreamData(const Json& format);

} // namespace YoutubeExplode::detail
