#pragma once

#include <YoutubeExplode/Common/Language.hpp>
#include <YoutubeExplode/Common/Time.hpp>

#include <optional>
#include <string>
#include <vector>

namespace YoutubeExplode::Videos::ClosedCaptions {

/// Metadata associated with a closed caption track.
class ClosedCaptionTrackInfo {
public:
    ClosedCaptionTrackInfo() = default;
    ClosedCaptionTrackInfo(std::string url, Common::Language language, bool isAutoGenerated)
        : url_(std::move(url)), language_(std::move(language)), isAutoGenerated_(isAutoGenerated) {}

    const std::string& url() const noexcept { return url_; }
    const Common::Language& language() const noexcept { return language_; }
    bool isAutoGenerated() const noexcept { return isAutoGenerated_; }

    std::string toString() const { return "CC Track (" + language_.toString() + ")"; }

private:
    std::string url_;
    Common::Language language_;
    bool isAutoGenerated_ = false;
};

/// Describes available closed caption tracks for a YouTube video.
class ClosedCaptionManifest {
public:
    ClosedCaptionManifest() = default;
    explicit ClosedCaptionManifest(std::vector<ClosedCaptionTrackInfo> tracks) : tracks_(std::move(tracks)) {}

    const std::vector<ClosedCaptionTrackInfo>& tracks() const noexcept { return tracks_; }

    /// Finds a track by language code or name (case-insensitive).
    std::optional<ClosedCaptionTrackInfo> tryGetByLanguage(const std::string& language) const;
    /// Throws std::out_of_range if no such track exists.
    ClosedCaptionTrackInfo getByLanguage(const std::string& language) const;

private:
    std::vector<ClosedCaptionTrackInfo> tracks_;
};

/// Individual word/segment inside a closed caption (auto-generated captions only).
class ClosedCaptionPart {
public:
    ClosedCaptionPart(std::string text, TimeSpan offset) : text_(std::move(text)), offset_(offset) {}

    const std::string& text() const noexcept { return text_; }
    /// Offset relative to the beginning of the parent caption.
    TimeSpan offset() const noexcept { return offset_; }

private:
    std::string text_;
    TimeSpan offset_;
};

/// Individual closed caption.
class ClosedCaption {
public:
    ClosedCaption(std::string text, TimeSpan offset, TimeSpan duration, std::vector<ClosedCaptionPart> parts)
        : text_(std::move(text)), offset_(offset), duration_(duration), parts_(std::move(parts)) {}

    const std::string& text() const noexcept { return text_; }
    TimeSpan offset() const noexcept { return offset_; }
    TimeSpan duration() const noexcept { return duration_; }
    const std::vector<ClosedCaptionPart>& parts() const noexcept { return parts_; }

    std::optional<ClosedCaptionPart> tryGetPartByTime(TimeSpan time) const;

private:
    std::string text_;
    TimeSpan offset_;
    TimeSpan duration_;
    std::vector<ClosedCaptionPart> parts_;
};

/// Track that contains closed captions in a specific language.
class ClosedCaptionTrack {
public:
    ClosedCaptionTrack() = default;
    explicit ClosedCaptionTrack(std::vector<ClosedCaption> captions) : captions_(std::move(captions)) {}

    const std::vector<ClosedCaption>& captions() const noexcept { return captions_; }

    /// Gets the caption displayed at the specified point in time.
    std::optional<ClosedCaption> tryGetByTime(TimeSpan time) const;

    /// Serializes the track in SubRip (.srt) format.
    std::string toSrt() const;

private:
    std::vector<ClosedCaption> captions_;
};

} // namespace YoutubeExplode::Videos::ClosedCaptions
