#include <YoutubeExplode/Exceptions.hpp>
#include <YoutubeExplode/Videos/ClosedCaptions/ClosedCaptionClient.hpp>

#include "../../Bridge/Manifests.hpp"
#include "../../ClientContext.hpp"
#include "../../Utils/StringUtils.hpp"
#include "../../Utils/Url.hpp"
#include "../VideoController.hpp"

#include <cstdio>
#include <fstream>
#include <sstream>
#include <stdexcept>

namespace YoutubeExplode::Videos::ClosedCaptions {

using namespace YoutubeExplode::detail;

// ---- Models ---------------------------------------------------------------------------------------

std::optional<ClosedCaptionTrackInfo> ClosedCaptionManifest::tryGetByLanguage(const std::string& language) const {
    for (const auto& t : tracks_)
        if (iequals(t.language().code(), language) || iequals(t.language().name(), language))
            return t;
    return std::nullopt;
}

ClosedCaptionTrackInfo ClosedCaptionManifest::getByLanguage(const std::string& language) const {
    auto track = tryGetByLanguage(language);
    if (!track)
        throw std::out_of_range("No closed caption track available for language '" + language + "'.");
    return *track;
}

std::optional<ClosedCaptionPart> ClosedCaption::tryGetPartByTime(TimeSpan time) const {
    for (const auto& p : parts_)
        if (p.offset() >= time)
            return p;
    return std::nullopt;
}

std::optional<ClosedCaption> ClosedCaptionTrack::tryGetByTime(TimeSpan time) const {
    for (const auto& c : captions_)
        if (time >= c.offset() && time <= c.offset() + c.duration())
            return c;
    return std::nullopt;
}

namespace {

std::string formatSrtTimestamp(TimeSpan value) {
    const long long ms = value.count();
    char buf[32];
    std::snprintf(buf, sizeof buf, "%02lld:%02lld:%02lld,%03lld", ms / 3600000, (ms / 60000) % 60, (ms / 1000) % 60,
                  ms % 1000);
    return buf;
}

std::string formatSrtEntry(std::size_t number, const ClosedCaption& caption) {
    std::string out = std::to_string(number) + "\n";
    out += formatSrtTimestamp(caption.offset()) + " --> " + formatSrtTimestamp(caption.offset() + caption.duration()) + "\n";
    // Caption text may itself contain SRT control sequences; SRT has no escaping, so replace the
    // dashes of the arrow with en-dashes, which look similar enough.
    out += replaceAll(caption.text(), "-->", "\xE2\x80\x93\xE2\x80\x93>") + "\n\n";
    return out;
}

} // namespace

std::string ClosedCaptionTrack::toSrt() const {
    std::string out;
    for (std::size_t i = 0; i < captions_.size(); ++i)
        out += formatSrtEntry(i + 1, captions_[i]);
    return out;
}

// ---- Client ---------------------------------------------------------------------------------------

ClosedCaptionManifest ClosedCaptionClient::getManifest(const VideoId& videoId,
                                                       const CancellationToken& cancellationToken) const {
    VideoController controller(*context_);
    auto response = controller.getPlayerResponse(videoId.value(), cancellationToken);
    std::vector<ClosedCaptionTrackInfo> tracks;
    for (const auto& t : response.closedCaptionTracks()) {
        if (!t.url)
            throw Exceptions::YoutubeExplodeException("Failed to extract the track URL.");
        if (!t.languageCode)
            throw Exceptions::YoutubeExplodeException("Failed to extract the track language code.");
        auto url = *t.url;
        if (startsWith(url, "/"))
            url = "https://www.youtube.com" + url;
        tracks.emplace_back(url, Common::Language(*t.languageCode, t.languageName.value_or(*t.languageCode)),
                            t.isAutoGenerated);
    }
    return ClosedCaptionManifest(std::move(tracks));
}

ClosedCaptionTrack ClosedCaptionClient::get(const ClosedCaptionTrackInfo& trackInfo,
                                            const CancellationToken& cancellationToken) const {
    // Enforce known format (srv3 XML)
    auto url = Url::setQueryParameter(Url::setQueryParameter(trackInfo.url(), "format", "3"), "fmt", "3");
    auto xml = context_->getString(url, cancellationToken);

    std::vector<ClosedCaption> captions;
    for (auto& data : parseClosedCaptionTrack(xml)) {
        // Skip over empty captions, but not captions containing only whitespace
        if (data.text.empty())
            continue;
        // Auto-generated captions may be missing offset or duration
        if (!data.offset || !data.duration)
            continue;
        std::vector<ClosedCaptionPart> parts;
        for (auto& p : data.parts) {
            if (p.text.empty())
                continue;
            parts.emplace_back(std::move(p.text), p.offset);
        }
        captions.emplace_back(std::move(data.text), *data.offset, *data.duration, std::move(parts));
    }
    return ClosedCaptionTrack(std::move(captions));
}

void ClosedCaptionClient::writeTo(const ClosedCaptionTrackInfo& trackInfo, std::ostream& writer,
                                  const Progress& progress, const CancellationToken& cancellationToken) const {
    const auto track = get(trackInfo, cancellationToken);
    const auto& captions = track.captions();
    for (std::size_t i = 0; i < captions.size(); ++i) {
        cancellationToken.throwIfCancellationRequested();
        writer << formatSrtEntry(i + 1, captions[i]);
        if (progress)
            progress(static_cast<double>(i + 1) / static_cast<double>(captions.size()));
    }
    writer.flush();
}

void ClosedCaptionClient::download(const ClosedCaptionTrackInfo& trackInfo, const std::string& filePath,
                                   const Progress& progress, const CancellationToken& cancellationToken) const {
    std::ofstream file(filePath, std::ios::binary | std::ios::trunc);
    if (!file)
        throw Exceptions::YoutubeExplodeException("Failed to open '" + filePath + "' for writing.");
    writeTo(trackInfo, file, progress, cancellationToken);
}

} // namespace YoutubeExplode::Videos::ClosedCaptions
